stages:
  - tests
  - build
  - deploy

black:
  stage: tests
  image: python:3.9
  script:
    - pip3 install poetry
    - poetry install
    - poetry run black -l 120 -t py38 --check .

build-develop:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build --pull -t "$CI_REGISTRY/postgres-syncer:latest" .
    - docker push "$CI_REGISTRY/postgres-syncer:latest"
  only:
    - master

tag-develop:
  stage: deploy
  image: binkops.azurecr.io/tagbot:latest
  before_script:
    - export CTAG=$(echo -n "$CI_PIPELINE_CREATED_AT" | sed s/\://g)
  script:
    - tagbot --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD" --source "$CI_REGISTRY/postgres-syncer:latest" --tag "develop-$CTAG"
  only:
    - master
