stages:
  - tests
  - build
  - deploy

black:
  stage: tests
  script:
    - pip3 install poetry
    - poetry install
    - poetry run black -l 120 -t py38 --check .

build-develop:
  stage: build
  image: terrycain/docker-env-creds:latest
  services:
    - docker:dind
  script:
    - docker build --pull -t "$CI_REGISTRY/postgres-syncer:latest" .
    - docker push "$CI_REGISTRY/postgres-syncer:latest"
  only:
    - master

tag-develop:
  stage: deploy
  image: binkops.azurecr.io/tagbot:latest
  script:
    - tagbot --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD" --source "$CI_REGISTRY/postgres-syncer:latest" --tag "develop-$CI_COMMIT_SHORT_SHA"
  only:
    - master
